language: android

jdk:
  - oraclejdk8

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

android:
  components:
    - tools
    - android-28
    - platform-tools

branches:
  except:
    - gh-pages

# Disable Travis container-based infrastructure to correct
# resource consumption in gradle presumably due to dexing.
sudo: true
